version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Eureka Server
  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  # User Service
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db

volumes:
  postgres-data: