server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
